# Generated by Django 5.2.4 on 2026-05-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skilltag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
