# Длины полей
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

# Пагинация
PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12

# Аватар
AVATAR_COLORS = [
    '#5B8DEF', '#9B59B6', '#E67E22',
    '#27AE60', '#E74C3C', '#16A085',
    '#2980B9', '#8E44AD', '#D35400',
]
AVATAR_SIZE = 100

# Статусы проекта
PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'
PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, 'Open'),
    (PROJECT_STATUS_CLOSED, 'Closed'),
]
